spring:
  application:
    name: mcpstudy

  datasource:
    url: jdbc:postgresql://localhost:5432/mcp_study
    username: mcp_user
    password: mcp_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: spring-mcp-study-server
        version: 0.1.0
        type: SYNC
        annotation-scanner:
          enabled: true
        streamable-http:
          mcp-endpoint: /mcp
